export const PROBLEM_FETCHING = "PROBLEM_FETCHING";
export const PROBLEM_SUCCESS = "PROBLEM_SUCCESS";
export const PROBLEM_FAILED = "PROBLEM_FAILED";


export const WORKLOAD_FETCHING = "WORKLOAD_FETCHING";
export const WORKLOAD_SUCCESS = "WORKLOAD_SUCCESS";
export const WORKLOAD_FAILED = "WORKLOAD_FAILED";

export const CALLIN_FETCHING = "CALLIN_FETCHING";
export const CALLIN_SUCCESS = "CALLIN_SUCCESS";
export const CALLIN_FAILED = "CALLIN_FAILED";


